### PR TITLE
Update Hashing.hs

### PR DESCRIPTION
**Pull request by peter-mlabs**

### CODE REVIEW

**Review by SeungheonOh — APPROVED** [review]
Either is fine, but maybe we want to expose this to haddock as well? So `--|` not `--`

**Comment by peter-mlabs** [comment]
Oh, this isn't replacing the comment. Just adding some lines.

**Comment by SeungheonOh** [comment]
Oh really?? Have I been using Haddock incorrectly since the beginning... I'll test it 

But tbh having | on every haddock comment line looks better.

**Review by SeungheonOh — APPROVED** [review]
Thanks!

**Pull request merged**
