### PR TITLE
Adds standard haskell tooling to the dev environment

### PR DESCRIPTION
**Pull request by bladyjoker**
DONE:
- [x] Adds hls, fourmolu, hlint, cabal, cabal-fmt to dev env
- [x] Splits Nix config in hercules-ci.nix and pre-commit.nix (smaller flake where the actual essence is)
- [x] Applies all linting checks

### CODE REVIEW

**Comment by SeungheonOh** [comment]
LGTM

**Comment by bladyjoker** [comment]
I'm having an issue reproducing the tests locally,

```
plutarch-plutus/plutarch-test on  bladyjoker/fix-missing-tools via λ 9.6.3 via ❄️  impure (ghc-shell-for-packages) took 54s 
❯ cabal run plutarch-test -- -m "/golden/"
Finished in 54.1897 seconds
135 examples, 55 failures
```

I don't understand where the difference originates but some of it is concerning.

Notice the difference in `lookup.hit` for example:

```
lookup.hit (program 1.0.0 (\i0 -> \i0 -> i2 42))
lookup.hit (program 1.0.0 (\i0 i0 -> i2 42))
```

The new version just looks wrong.

A bigger output suggests there are some formatting differences...

```diff
  5) Plutarch.Api.api.map.golden uplc.eval                                                                                                                                                                                                     
       expected: lookup.itself (program 1.0.0 (\i0 -> (\i0 -> \i0 -> \i0 -> (\i0 -> (\i0 -> i2 (\i0 -> i2 i2 i1)) (\i0 -> i2 (\i0 -> i2 i2 i1))) (\i0 -> \i0 -> force (force (force chooseList) i1 (delay (\i0 -> \i0 -> force i1)) (delay (for
ce (force ifThenElse (equalsData (force (force fstPair) (force headList i1)) i4) (delay (i5 (force headList i1))) (delay (i2 (force tailList i1)))))))) i1) (\i0 -> (\i0 -> \i0 -> \i0 -> i2 i3) (unIData (force (force sndPair) i1))) (bData i1)))
                 lookup.hit (program 1.0.0 (\i0 -> \i0 -> i2 42))
                 lookup.miss (program 1.0.0 (\i0 -> \i0 -> force i1))
                 lookupData.hit (program 1.0.0 (\i0 -> \i0 -> i2 #182a))
                 lookupData.miss (program 1.0.0 (\i0 -> \i0 -> force i1))
                 findWithDefault.itself (program 1.0.0 (\i0 -> \i0 -> (\i0 -> \i0 -> \i0 -> \i0 -> (\i0 -> (\i0 -> i2 (\i0 -> i2 i2 i1)) (\i0 -> i2 (\i0 -> i2 i2 i1))) (\i0 -> \i0 -> force (force (force chooseList) i1 (delay i5) (delay (force (force ifThenElse (equalsData (force (force fstPair) (force headList i1)) i6) (delay (i4 (force (force sndPair) (force headList i1)))) (delay (i2 (force tailList i1)))))))) i1) (bData i1) i2 unIData))
                 findWithDefault.hit (program 1.0.0 42)
                 findWithDefault.hit2 (program 1.0.0 6)
                 findWithDefault.miss (program 1.0.0 12)
                 @@ 34 lines omitted @@
                  
        but got: lookup.itself (program 1.0.0 (\i0 ->
                                   (\i0
                                     i0
                                     i0 ->
                                      (\i0 ->
                                         (\i0 -> i2 (\i0 -> i2 i2 i1))
                                           (\i0 -> i2 (\i0 -> i2 i2 i1)))
                                        (\i0
                                          i0 ->
                                           force (force (force chooseList)
                                                    i1
                                                    (delay (\i0 i0 -> force i1))
                                                    (delay (force (force ifThenElse
                                                                     (equalsData
                                                                        (force (force fstPair)
                                                                           (force headList i1))
                                                                        i4)
                                                                     (delay (i5
                                                                               (force headList
                                                                                  i1)))
                                                                     (delay (i2
                                                                               (force tailList
                                                                                  i1))))))))
                                        i1)
                                     (\i0 ->
                                        (\i0 i0 i0 -> i2 i3)
                                          (unIData (force (force sndPair) i1)))
                                     (bData i1)))
                 lookup.hit (program 1.0.0 (\i0 i0 -> i2 42))
                 lookup.miss (program 1.0.0 (\i0 i0 -> force i1))
                 lookupData.hit (program 1.0.0 (\i0 i0 -> i2 #182a))
                 lookupData.miss (program 1.0.0 (\i0 i0 -> force i1))
                 findWithDefault.itself (program 1.0.0 (\i0 
                                  i0 ->
                                   (\i0
                                     i0
                                     i0
                                     i0 ->
                                      (\i0 ->
                                         (\i0 -> i2 (\i0 -> i2 i2 i1))
                                           (\i0 -> i2 (\i0 -> i2 i2 i1)))
                                        (\i0
                                          i0 ->
                                           force (force (force chooseList)
                                                    i1
                                                    (delay i5)
                                                    (delay (force (force ifThenElse
                                                                     (equalsData
                                                                        (force (force fstPair)
                                                                           (force headList i1))
                                                                        i6)
                                                                     (delay (i4
                                                                               (force (force sndPair)
                                                                                  (force headList
                                                                                     i1))))
                                                                     (delay (i2
                                                                               (force tailList
                                                                                  i1))))))))
                                        i1)
                                     (bData i1)
                                     i2
                                     unIData))
                 findWithDefault.hit (program 1.0.0 42)
                 findWithDefault.hit2 (program 1.0.0 6)
                 findWithDefault.miss (program 1.0.0 12)
```

**Comment by SeungheonOh** [comment]
Here are some reasoning and notes behind to why goldens have changed:
- We use plutus-core function `prettyPlcReadableDebug` to print UPLC, they don't seem to be consistent across plutus-core versions. 
- We can deprecate Plutarch.Pretty, we don't use it and we don't needed it as we can use the one from plutus-core
- New generated goldens seems okay, I think only some indentation have changed.

**Comment by TotallyNotChase** [comment]
I think Plutarch.Pretty is used by others downstream. It's goal was to be used by users. Not in the library itself

**Comment by SeungheonOh** [comment]
It does give a slightly more helpful output, that is not just raw lambda applications and showing let-ins. To keep it or not is not under scope of this PR, so we can discuss it later

**Comment by SeungheonOh** [comment]
The golden does seem correct. What's changed is that new golden combines multiple lambda arguments into one. They call it iterated lambda, and they did not make any option to disable this. Also, new one has nicer newlines. This we can turn off and make it look similar to out golden by changing this: 
```hs
printScript = PPS.renderString  . (PP.layoutPretty $ PP.LayoutOptions PP.Unbounded) . prettyPlcReadableDebug . (\(Script s) -> s)
```

I think we can just keep it as is

**Review by SeungheonOh — APPROVED** [review]

**Pull request merged**
