### PR TITLE
Bumping to latest plutus(1.7.0.0)

### PR DESCRIPTION
**Pull request by SeungheonOh**

### CODE REVIEW

**Comment by L-as** [comment]
I wonder why CI is broken

**Comment by SeungheonOh** [comment]
I changed the flake. Old mlabs-tooling doesn't use CHaP and is deprecated, and liqwid-nix ships with Plutarch by default.

I'm taking a look at flake today.

**Comment by SeungheonOh** [comment]
Oh, yeah. I'll do that too

**Comment by SeungheonOh** [comment]
replaced by #620

**Pull request closed without merging**
