### PR TITLE
Tagging evaluated terms

### PR DESCRIPTION
**Pull request by SeungheonOh**
#540

### CODE REVIEW

**Comment by SeungheonOh** [comment]
We can make `pconstant` and `pcon` to return evaluated term in right cases, and I tried it. But that would be a more significant rewrites and I'm not sure if that's what we want to do.

**Comment by L-as** [comment]
This is a very big change that is also incompatible with Plutarch 2.0. It's not clear to me why you need this though, what's wrong with having a `EvaluatedTerm` newtype?

**Comment by SeungheonOh** [comment]
new type wrapper requires having a whole use sets of functions rewritten for evaluated terms. Instead, having this tag allows us to use what Plutarch itself offers like papp.

Best,
Seungheon Oh
***@***.***
________________________________

**Comment by SeungheonOh** [comment]
new type wrapper requires having a whole use sets of functions rewritten for evaluated terms. Instead, having this tag allows us to use what Plutarch itself offers like papp.

________________________________

**Comment by SeungheonOh** [comment]
Actually, I getting more skeptical about this because it's largely confusing to use and write codes on it. While it would still be very helpful to use operators from Plutarch itself when using EvaluatedTerm, this is a too much effort just for that.

**Pull request closed without merging**
