### PR TITLE
PlutusV3 Feature Support

### PR DESCRIPTION
**Pull request by colll78**
## Added
* Cryptographic hashing utilities:- `pripemd_160`, `pkeccak_256`, and `pblake2b_224` to `Plutarch.Crypto`
* PlutusV3 BLS primitives to `Plutarch.BLS`
* PlutusV3 Bitwise primitives to `Plutarch.Bitwise`

## Changed
* Bumped `plutus-core` version to `1.33.0.0`
* Updated `getArity` mapping to handle the new builtins in `Plutarch.Internal`
* Updated `printScript` in `Plutarch.Internal.Other` to new PlutusCore version.

@peter-mlabs 
@SeungheonOh 
Review please.

### CODE REVIEW

**Review by kozross — CHANGES_REQUESTED** [review]
Only thing needed is a bunch of `@since`s, as well as a major version bump (Plutus dep bump).

**Comment by SeungheonOh** [comment]
Primops added are 
- [CIP-122 Bitwise primops on ByteString](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0122)
- [CIP-123 Logical primops on ByteString](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0123)
- [CIP-381 BLS12-381 primops](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0381)
- [CIP-101 keccak256 primop](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0101)
- [CIP-127 ripemd_160 primop](https://github.com/cardano-foundation/CIPs/pull/826)

Implementations looks good to me, it can use little documentations, but that can be added later

**Review by SeungheonOh — APPROVED** [review]
Thank you. Looks good to me. Ideally we push some tests as well. I'll see if I can pull some time somewhere to work on it hopefully.

**Comment by colll78** [comment]
> Thank you. Looks good to me. Ideally we push some tests as well. I'll see if I can pull some time somewhere to work on it hopefully.

module Testing.Crypto where

import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.QuickCheck as QC
import Testing.Eval (psucceeds, passert, toHexString)
import Plutarch.Prelude
import PlutusCore.Crypto.Hash qualified as Hash

```haskell
tests :: TestTree
tests = testGroup "PlutarchV3 Builtins"
  [ testCase "keccak_256" $
      passert $
        (pkeccak_256 # (phexByteStr "4dd6d57ca8cb7ac8c3b219366754a392ba9e4e43b6b3ae59d89be3f878ba8fb6")) 
            #== phexByteStr "1994466d51e80d6dc32c8f41f142b47b2d03b4f5fa869aced6157c016b2b331d"
  , testCase "pblake2b_224" $
      passert $
        (pblake2b_224 # (phexByteStr "4dd6d57ca8cb7ac8c3b219366754a392ba9e4e43b6b3ae59d89be3f878ba8fb6")) 
            #== pconstant (Hash.blake2b_224 $ toHexString "4dd6d57ca8cb7ac8c3b219366754a392ba9e4e43b6b3ae59d89be3f878ba8fb6")
  , testCase "pripemd_160" $
      passert $
        (pripemd_160 # (phexByteStr "4dd6d57ca8cb7ac8c3b219366754a392ba9e4e43b6b3ae59d89be3f878ba8fb6")) 
            #== pconstant (Hash.ripemd_160 $ toHexString "4dd6d57ca8cb7ac8c3b219366754a392ba9e4e43b6b3ae59d89be3f878ba8fb6")
  ]
```

**Pull request merged**
